# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(default='titlte', max_length=20),
            preserve_default=False,
        ),
    ]
